services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: unless-stopped # Automatically restart unless the service is explicitly stopped
    volumes:
      - laravel-public:/var/www/html/public:ro
    networks:
      - laravel
    ports:
      - "8080:80"
    depends_on:
      php-fpm:
        condition: service_healthy  # Wait for php-fpm health check

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - laravel-public:/var/www/html/public
    env_file:
      - .env
    networks:
      - laravel
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  laravel:

volumes:
  laravel-public: