apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: app-php
        image: magnocarlos1988/teste-tecnico_analista-devops:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-app
spec:
  selector:
    app: php-app
  ports:
  - port: 80
    targetPort: 80
  type: NodePort