name: CI Build Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:
    outputs:
      tag-image:
        value: ${{ jobs.CI.outputs.short-tag }}
  
jobs:
  CI:
    runs-on: ubuntu-latest
    outputs: 
      short-tag: ${{ steps.meta.outputs.SHORT_SHA }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            magnocarlos1988/teste-tecnico_analista-devops:${{ steps.meta.outputs.SHORT_SHA }}
            magnocarlos1988/teste-tecnico_analista-devops:latest
      
      - name: Docker Scout
        id: docker-scout-environment
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations
          image: magnocarlos1988/teste-tecnico_analista-devops:latest
          organization: ${{ vars.DOCKERHUB_USERNAME }}
          only-serity: critical
          exit-code: false
  